#!/bin/bash

cd $HOME
DIRECTORY=$HOME/facetimehd-firmware
if [ -d "$DIRECTORY" ]; then
	mv $DIRECTORY $DIRECTORY".old"
fi
git clone https://github.com/patjak/facetimehd-firmware.git
cd facetimehd-firmware
make
sudo make install
git clone https://github.com/patjak/bcwc_pcie.git
cd bcwc_pcie
make
sudo make install
sudo depmod
sudo modprobe facetimehd
